server:
  port: 9090
  

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

#client_secret: tika
#client_secret: kibana
spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/sbbEY152C6?createDatabaseIfNotExist=true
    username: sbbEY152C6
    password: qjndDIkjuz 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: profile
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: blakol-tika
      client-secret: tika
