server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/xmyzNqadUy?createDatabaseIfNotExist=true
    username: xmyzNqadUy
    password: TosnGPNJur
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
#client_secret: tika
#client_secret: kibana